<?php
/**
 * AddressHunter
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/BSD-3-Clause
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@addresshunter.net so we can send you a copy immediately.
 *
 * @package   AddressHunter
 * @copyright Copyright (c) 2011 skobbler GmbH (http://www.skobbler.com)
 * @license   http://www.opensource.org/licenses/BSD-3-Clause	 New BSD License
 * @version   $Id$
 */

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @copyright Copyright (c) 2011 skobbler GmbH (http://www.skobbler.com)
 * @license   http://www.opensource.org/licenses/BSD-3-Clause	 New BSD License
 */
class Application_Model_Addresshunter_AddressRepository extends EntityRepository
{
	/**
	 * Retrieves the available addresses in a given area (bounding box).
	 *
	 * An address is available if it was not yet used and found in a previous game or if it's not
	 * currently assigned in another game.
	 *
	 * NOTE: It is possible for an assigned address to become available again if the game is
	 * abandoned or expires and the address is not found.
	 *
	 * @param array $boundingBox Array with keys: xmax, xmin, ymax, ymin
	 * @param integer $limit Number of results to return
	 * @return array of Application_Model_Addresshunter_Address object
	 */
	public function getAvailableAddresses($boundingBox, $limit)
	{
		$query = $this->_em->createQuery('SELECT a FROM Application_Model_Addresshunter_Address a
										  WHERE a.approxX <= ?1 AND
												a.approxX >= ?2 AND
												a.approxY <= ?3 AND
												a.approxY >= ?4 AND
												a.isAvailable = 1
											'
										);
		$query->setMaxResults($limit);
		$query->setParameter(1, $boundingBox['xmax']);
		$query->setParameter(2, $boundingBox['xmin']);
		$query->setParameter(3, $boundingBox['ymax']);
		$query->setParameter(4, $boundingBox['ymin']);

		$result = $query->execute();

		return $result;
	}
}
