				<!-- ABOUT -->
				<p style="text-align:center">
					version <?php print $this->version['v']; ?> (#<?php print $this->version['rev']; ?>)
					<!--<br />(OSM server: <?php print $this->version['osm']; ?>)-->
				</p>
				<div style="font-size:14px; margin: 2% 8%;">
					<br />
					<p>&copy;2011 <a href="http://www.skobbler.com" target="_blank">skobbler</a> GmbH. All rights reserved.</p>
					<p>Map data <a href="http://creativecommons.org/licenses/by-sa/3.0/" target="_blank">CCBYSA</a> 2010 <a href="http://openstreetmap.org" target="_blank">OpenStreetMap.org</a></p>
					<p>Tiles Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a></p>
					<p>Collected addresses will become part of <a href="http://openstreetmap.org" target="_blank">OpenStreetMap</a> data.</p>
				</div>
